//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPOpenHouseAdminConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserResponse
    {
        public int ID { get; set; }
        public string userIDFK { get; set; }
        public int questionIDFK { get; set; }
        public string userAnswer { get; set; }
        public bool isCorrect { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
